sources:
  - name: raw_cb
    database: ADEBNEYDEMODB
    schema: raw_cb
    tables:
      - name: citybike_trips
        description: "Trips taken for the month"
      - name: weather strutured
        description: "Weather during trips"